modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/jaredlll08/Controlling/issues"
license="MIT"

[[mods]]
modId="controlling"
updateJSONURL="https://updates.blamejared.com/get?n=controlling&gv=1.16.5"
version="${file.jarVersion}"
displayName="Controlling"
displayURL="https://minecraft.curseforge.com/projects/controlling"
authors="Jaredlll08"
description='''
Adds the ability to search for keybinds using their name in the KeyBinding menu, this allows players to easily find a key binding in the menu.
'''
itemIcon="minecraft:compass"
  [[dependencies.controlling]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="CLIENT"
  [[dependencies.controlling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="CLIENT"